### ISSUE TITLE
Improperly parsed string when updating cluster service principal secret

### ISSUE THREAD

**Issue by guitmz** [Azure/AKS#1009]
Not sure if this issue should be in AKS repository. I was not able to tell if the problem is AKS engine, CLI or even Azure API itself. Let me know if you need me to move this to the proper communication channel.

**What happened**:
My client secret for cluster service principal expired. I have created a new one using the portal. It's random, auto generated and contains special characters (such as `+` sometimes).

Afterwards, I proceed to update my cluster credentials using the `az` command line:

```
az aks update-credentials \
    --resource-group myResourceGroup \
    --name myCluster \
    --reset-service-principal \
    --service-principal $SP_ID \
    --client-secret $SP_SECRET
```

The problem is that when running this command and having a secret that contains `+`, it gets parsed incorrectly and becomes `&#43;` (ascii for `+`) inside the kubernetes node in `/etc/kubernetes/azure.json` file, causing authentication issues (i.e ` Invalid client secret is provided`).

I have tried enclosing the secret with double quotes, single quotes and also without any quotes and the results were the same.

This can potentially be an issue with other characters as well.

**What you expected to happen**:
Secret to be updated properly inside kubernetes nodes, without parsing issues.

**How to reproduce it (as minimally and precisely as possible)**:
1. Generate new app secret that contains `+`
2. Use the command above to update it in kubernetes

**Anything else we need to know?**:

Suggestion: allow users to input the secret they want in the portal and fix this parsing issue or stop including problematic characters in the random secret.

**Environment**:
- Kubernetes version : **v1.13.5**
- Size of cluster: **22**

**Comment by pdressel** [comment]
Until there is a fix, you can reliably rotate the credentials by resetting the client secret [directly via the cli](https://docs.microsoft.com/en-us/azure/aks/update-credentials#update-the-service-principal-credentials):

```
SP_ID=$(az aks show --resource-group myResourceGroup --name myAKSCluster \
    --query servicePrincipalProfile.clientId -o tsv)
SP_SECRET=$(az ad sp credential reset --name $SP_ID --query password -o tsv)
```

this generates a password without incorrectly parsed characters. You can then update the cluster like above with:

```
az aks update-credentials \
    --resource-group myResourceGroup \
    --name myAKSCluster \
    --reset-service-principal \
    --service-principal $SP_ID \
    --client-secret $SP_SECRET
```

**Comment by ridhoq** [comment]
+1. This is documented in this blog post: https://www.jbmurphy.com/2019/03/13/aks-you-update-credentials-and-cant-pull-from-your-acr/

**Comment by arjovanramshorst** [comment]
When using the method specified above, I get the following error:

```
$ az aks update-credentials -g $GROUP_NAME -n $CLUSTER_NAME --reset-service-principal --service-principal $SP_ID --client-secret $SP_SECRET
Deployment failed. Correlation ID: a76090a0-29fe-46aa-9ffa-0518de51b65e. Internal server error
```
Any idea what causes this and if there is a workaround? I currently am unable to pull new images from the ACR, since the old secret has expired, and have been struggling with this now for a while

**Comment by palma21** [comment]
@weinong could you take a look?

**Comment by TomGeske** [comment]
We are looking into it.

**Comment by weinong** [comment]
@palma21 @TomGeske the last reported time was ... a year ago. not sure if there is anything to look at.

**Comment by TomGeske** [comment]
I was able to repro.

**Comment by guitmz** [comment]
yeah I check this every month or so since I reported it and I'm always able to reproduce...

**Comment by SteveCurran** [comment]
This is preventing us from implementing an automated way implementing security best practices. Right now it has to be manual to get this to periodically work. Not sure why this is not fixed yet.

**Comment by miwithro** [comment]
@xuto2 can you assist here?

**Comment by miwithro** [comment]
Hello,  this problem is mitigated if you leverage a Managed Identity over a Service Principal.  Can you give that a try.  We have just released in preview a way to migrate a cluster from SP to MSI too.

https://docs.microsoft.com/en-us/azure/aks/use-managed-identity

**Comment by wout-scorito** [comment]
Is there any update for a fix on this?

**Comment by jpepp32** [comment]
Leaving his comment incase it will help someone...

I've see this error when trying to update the SP too soon after making it.

So, even after creating a secret without ' ~ ' , ' - ', ' + ', or ' . '  using a while loop,  it was still failing.
BUT, I could take that failed secret and run the same command manually 30s later, and it would work... odd.

So, I added a 2m sleep to my script, and that seems to work.
