### ISSUE TITLE
Unable to connect to newly created AKS cluster

### ISSUE THREAD

**Issue by alexxie** [Azure/AKS#137]
1. create cluster using CLI: az aks create --resource-group aks-res-group-cluster --name mypoc --node-count 1 --generate-ssh-keys
2. cluster is created 
3. get credential: az aks get-credentials --resource-group=aks-res-group-cluster --name=mypoc
4. kubectl get nodes fails:
Unable to connect to the server: dial tcp: lookup mypoc-aks-res-group-cl-9288d9-7b245a82.hcp.eastus.azmk8s.io: no such host

any idea?

**Comment by swgriffith** [comment]
I hit this same issue last night, but it seems to have been resolved for me now.

**Comment by alexxie** [comment]
confirmed the issue is resolved overnight.

**Comment by MatthewHartstonge** [comment]
I've just deployed a new cluster, and still having this issue, but I'm getting:
`Unable to connect to the server: net/http: TLS handshake timeout`

**Comment by tim-wilcoxson** [comment]
Getting the same issue right now. 

Unable to connect to the server: dial tcp: no such host

**Comment by grohan2002** [comment]
I still get the same issue : I am using a Jenkins Template from Azure and creating AKS using Azure-CLI 2.0.25

Error :+1: 
jenkins@jenkins:~$ az aks create --resource-group simplimedaks-new-rg --name simplimedaks-new --node-count 2 --generate-ssh-keys   --kubernetes-version 1.8.1
{
  "agentPoolProfiles": [
    {
      "count": 2,
      "dnsPrefix": null,
      "fqdn": null,
      "name": "nodepool1",
      "osDiskSizeGb": null,
      "osType": "Linux",
      "ports": null,
      "storageProfile": "ManagedDisks",
      "vmSize": "Standard_D1_v2",
      "vnetSubnetId": null
    }
  ],
  "dnsPrefix": "simplimeda-simplimedaks-new-4ad96d",
  "fqdn": "simplimeda-simplimedaks-new-4ad96d-c2b29752.hcp.eastus.azmk8s.io",
  "id": "/subscriptions/4ad96def-97a4-40aa-8c13-0c5cd6d2a15a/resourcegroups/simplimedaks-new-rg/providers/Microsoft.ContainerService/managedClusters/simplimedaks-new",
  "kubernetesVersion": "1.8.1",
  "linuxProfile": {
    "adminUsername": "azureuser",
    "ssh": {
      "publicKeys": [
        {
          "keyData": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQChGNV7XhzyDOpIgUbpMPtIE2gIMdo3OfxL2eYskRLMOcVY5SMBIjxHcDft/FGqJ5Z8Sw46zxgdMKZFXrlgTf0M8gsPdoh1UtwQOdsOrd+MnhnVL4sznJcf2itAdaN3AeuDgESKO0jtxiIO9Em609XM1aPx8JhmOSaWLwJe+dtafKrEwOZiLFd0CsJ2CFM37lceNGOwaed1MIfCNqtFE5TzrMkKD7ok/dV6aOKMqb/uvVZcIhM9Mt44nLEzLMCpp6JgZSOGMx59fnCuxtbXdz4JJtUCFNn+u/oO7Eb7B8LjCMvwVvm914ehN5EkQ+d98uX60NYna5z0HzPEFMPiRZkV"
        }
      ]
    }
  },
  "location": "eastus",
  "name": "simplimedaks-new",
  "provisioningState": "Succeeded",
  "resourceGroup": "simplimedaks-new-rg",
  "servicePrincipalProfile": {
    "clientId": "75fcc839-2430-4cb5-804e-5553b56cb673",
    "keyVaultSecretRef": null,
    "secret": null
  },
  "tags": null,
  "type": "Microsoft.ContainerService/ManagedClusters"
}
jenkins@jenkins:~$ sudo az aks install-cli
Downloading client to /usr/local/bin/kubectl from https://storage.googleapis.com/kubernetes-release/release/v1.9.2/bin/linux/amd64/kubectl
jenkins@jenkins:~$ az aks get-credentials --resource-group=simplimedaks-new-rg --name=simplimedaks-new
Merged "simplimedaks-new" as current context in /home/jenkins/.kube/config
jenkins@jenkins:~$ kubectl get node -o wide
Unable to connect to the server: dial tcp: lookup simplimeda-simplimedaks-new-4ad96d-c2b29752.hcp.eastus.azmk8s.io on 168.63.129.16:53: no such host

**Comment by ylhyh** [comment]
If you enabled "Private cluster" feature, you can disable "Private cluster" when you creating k8s cluster
