### ISSUE TITLE
[BUG] Enabling secret store CSI driver from Azure Portal creates null config

### ISSUE THREAD

**Issue by zioproto** [Azure/AKS#3045]
Enabling secret store CSI driver from Azure Portal creates null config
```
$ az aks show -n {} -g {}  | jq .addonProfiles.azureKeyvaultSecretsProvider.config
null
```
This is consistent both at cluster creation or updating the Cluster Configuration later with the Azure Portal.

When enabling the same addon from the `az` cli you get:
```
$ az aks show -n {} -g {} -o json | jq .addonProfiles.azureKeyvaultSecretsProvider.config
{
  "enableSecretRotation": "true",
  "rotationPollInterval": "2m"
}

```

This behavior is the root cause for bug https://github.com/Azure/azure-cli/issues/23051 that fails with a python TypeError because `null` is not expected in `.addonProfiles.azureKeyvaultSecretsProvider.config`

**To Reproduce**
1. Create a AKS cluster with the Azure Portal and enable the secret store CSI drive addon.
2. Run `az aks show -n {} -g {}  | jq .addonProfiles.azureKeyvaultSecretsProvider.config` and verify the output.

**Expected behavior**
This bug is to clarify the expected behaviour.
* If `null` is a valid value, then in https://github.com/Azure/azure-cli/issues/23051  the CLI should be patched to handle this.
* If `null` is not a valid value, the AKS API should not accept the API call from Azure Portal that leads to the `null` config.

**Environment:**
 -  CLI Version azure-cli 2.37.0
 -  Kubernetes version 1.23

**Comment by raghulmsft** [comment]
Thanks for sharing this with us. I'll work with the team to look into.

**Comment by zioproto** [comment]
@raghulmsft Looking at the [Create or Update API](https://docs.microsoft.com/en-us/rest/api/aks/managed-clusters/create-or-update?tabs=HTTP) the [ManagedClusterAddonProfile](https://docs.microsoft.com/en-us/rest/api/aks/managed-clusters/create-or-update?tabs=HTTP#managedclusteraddonprofile) is very generic because it is the skeleton for any addon.

I cant find for the specific addon `azureKeyvaultSecretsProvider` the REST API documentation. I want to understand if an API call with an empty `config` is a valid API call.

The `azure-cli` folks fixed this problem on their side forcing a new API call that will populate the `config` with the default values: https://github.com/Azure/azure-cli/pull/23088

While this workaround fixes the issue for `azure-cli`, there are other clients consuming the API, like Terraform for example.
We need to understand if `config` is allowed to be empty or not.

It the `config` cannot be empty, the AKS API endpoint should reject the API call when a request with an empty `config` comes in.

**Comment by chandraneel** [comment]
This was resolved long time ago. Can we mark it as done?

**Comment by chandraneel** [comment]
This issue is fixed and live in all regions.

**Comment by zioproto** [comment]
Hello,
I just created an AKS cluster with the portal (AKS version 1.23.12)

I confirm the config is now correct, and it is not `null` anymore when **creating** a new cluster.

```
az aks show -n test -g test -o json | jq .addonProfiles.azureKeyvaultSecretsProvider.config
{
  "enableSecretRotation": "false",
  "rotationPollInterval": "2m"
}
```

However, if the cluster is created with  secret store CSI driver *disabled*, and then is *enabled* with the portal, I get again the `null` config:

```
az aks show -n test2 -g test2 -o json | jq .addonProfiles.azureKeyvaultSecretsProvider.config
null
```

more info:

```
 az aks show -n test2 -g test2 -o json | jq .addonProfiles.azureKeyvaultSecretsProvider
WARNING: The behavior of this command has been altered by the following extension: aks-preview
{
  "config": null,
  "enabled": true,
  "identity": {
    "clientId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "objectId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "resourceId": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/MC_test2_test2_eastus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/azurekeyvaultsecretsprovider-test2"
  }
}
```

**Comment by chandraneel** [comment]
Thanks @zioproto for checking this. Taking another look.

**Comment by zioproto** [comment]
@raghulmsft why this was closed as completed ?
In comment https://github.com/Azure/AKS/issues/3045#issuecomment-1322483538 I pointed out that the fix works only when creating a cluster but the bug is still there when updating a cluster.
I believe @chandraneel is still looking into this. Would it please be possible to open the issue again ? thanks

**Comment by raghulmsft** [comment]
Reopening to investigate the null config in the portal manage experience.

**Comment by rechevarria** [comment]
Fixed was applied to solve this, but we are currently in deployment lockdown.  Next deployment will be on 11/29.  Expect a little over 1week before changes reflect on portal.

**Comment by zioproto** [comment]
I tested again, and now from the portal I am not able to enable "Enable secret store CSI driver" anymore. The operation seems to fail silently after a few minutes of clicking the "apply" button.

**Comment by zioproto** [comment]
Steps to reproduce:
```
az aks create \
--location eastus \
--name test3 \
--resource-group myrg123 \
--network-plugin azure \
--kubernetes-version 1.23.12 \
--node-vm-size Standard_DC4s_v2 \
--node-count 1
```
Wait for the AKS cluster to be provisioned completely.

Go to the Portal, select the checkbox and apply ( see screenshot ).

![Screenshot 2022-12-05 at 10 58 11](https://user-images.githubusercontent.com/789701/205609079-0938a6a0-880b-4171-8838-9f39e44283eb.png)

---

**It says Update In Progress but the feature is never activated.**

---

![Screenshot 2022-12-05 at 10 59 44](https://user-images.githubusercontent.com/789701/205609123-8a842865-252f-4448-9b0e-3353666a30e4.png)

**Comment by rechevarria** [comment]
I tested in ms.portal.azure.com and its currently working.  azureKeyvaultSecretsProvider.config was null before the enabling the secret store CSI driver in portal, please see screenshot 
![image](https://user-images.githubusercontent.com/71800358/205708583-a07634a5-2362-4863-9645-bcd859166775.png)

Then, after enabling it and waiting for the save notification to complete azureKeyvaultSecretsProvider.config has correct value.  Please see screenshot 
![image](https://user-images.githubusercontent.com/71800358/205708862-26627851-7d70-4121-98d8-9c4ea01eec5c.png)

**Comment by zioproto** [comment]
Hello Folks,
after 1 month I am trying to reproduce again the steps at comment https://github.com/Azure/AKS/issues/3045#issuecomment-1337062727

I get again the same error, "update in progress" but nothing happens.

Using the browser developer tools I see `TypeError: Cannot set properties of undefined (setting 'azureKeyvaultSecretsProvider')`

![Screenshot 2023-01-05 at 07 52 58](https://user-images.githubusercontent.com/789701/210719746-713ccaf0-bb72-412c-9fea-fceb92d8ba7b.png)

**Comment by haugerbr** [comment]
@miwithro @zioproto Azure Portal team is looking into this and have a fix in review for this most recent issue.

**Comment by haugerbr** [comment]
A deployment with the fix is in progress and can be previewed at http://preview.portal.azure.com
