### ISSUE TITLE
Ingress whitelisting ip does not work

### ISSUE THREAD

**Issue by YvonneArnoldus** [Azure/AKS#438]
I'm using the following AKS configuration:

- Kubernetes version: 1.9.6
- stable/nginx-ingress  CHART VERSION:  0.20.1  APP VERSION:  0.14.0

I have the following ingress.yml

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fontoxml-dev-restricted-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: "xxx.xxx.xxx.xxx"
spec:
  tls:
  - hosts:
    - restricted.xxx.xxx
    secretName: my-host-com-secret
  rules:
  - host: restricted.xxx.xxx
    http:
      paths:
      - path: /
        backend:
          serviceName: restricted-example-staging
          servicePort: 80
```
I've have blurred out my real ip and domain.

If I connect to restricted.xxx.xxx on my ip xxx.xxx.xxx.xxx I get a 403.

I have checked with the [kubernetes/ingress-nginx](https://github.com/kubernetes/ingress-nginx) to see if my configuration was wrong. But the rule is added to the nginx.conf.

```
# Deny for restricted.xxx.xxx/
geo $the_real_ip $deny_qvkHIYSeUBWaPulBjeHzAGWwbBlksOdG {
		default 1;

		xxx.xxx.xxx.xxx 0;
}
```

They suggested to check and see if the load balancer forwards the ip that request the application or its own ip.

I'm not sure how to check this with the load balancer of AKS. Or if this can indeed be the case.

**Comment by joakimhellum-in** [comment]
The Azure documentation ([Install an ingress](https://docs.microsoft.com/en-us/azure/aks/ingress#install-an-ingress-controller)) suggests to install ingress controller with the command:
```
helm install stable/nginx-ingress --namespace kube-system
```
The documentation for [nginx-ingress helm chart](https://github.com/kubernetes/charts/tree/master/stable/nginx-ingress) suggests to set `controller.service.externalTrafficPolicy` to `Local` if `controller.service.type` is `NodePort` or `LoadBalancer`, to preserve the source IP of the request for filtering.

Maybe you could try to install the ingress controller with the following command:
```
helm install stable/nginx-ingress --namespace kube-system --set controller.service.externalTrafficPolicy=Local
```

**Comment by YvonneArnoldus** [comment]
@joakimhellum-in thank you for the example. 

I have tried your suggestion but I still receive a 503.

I have also upgraded stable/nginx-ingress to
CHART VERSION: 0.22.0 APP VERSION: 0.15.0

**Comment by pavius** [comment]
I'm using AKS w/nginx-ingress configured with a static IP bound to the AKS load balancer (installed nginx-ingress chart with `controller.service.loadBalancerIP=<the IP>`, after having received this IP address as per [this guide](https://docs.microsoft.com/en-us/azure/aks/static-ip). 

I initially tried to assign `nginx.ingress.kubernetes.io/whitelist-source-range` in one of my ingress resources but saw 403 when accessing from the whitelisted range. Checking the nginx ingress logs (`kubectl logs -f -n kube-system deploy/nginx-ingress-controller`) proved that the client source IP was not being preserved (it is logged at the beginning).

Reinstalling nginx-ingress with `--set controller.service.externalTrafficPolicy=Local` (which is `Cluster` by default) as per @joakimhellum-in's comment did the trick. From the [Kubernetes docs](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/) on the subject:

```
There are two available options: “Cluster” (default) and “Local”. “Cluster” obscures the client source IP and may cause a second hop to another node, but should have good overall load-spreading. “Local” preserves the client source IP and avoids a second hop for LoadBalancer and NodePort type services, but risks potentially imbalanced traffic spreading.
```

**Comment by Mumrau** [comment]
@YvonneArnoldus 503 is Service Unavailable which differs from 403 being Access Forbidden.
I suspect that your problem is due to a misconfiguration in the target service, in addition to the (eventually) resolved as suggested (and worked in my configuration) by @joakimhellum-in .

I suggest you check the ports and the configuration of the target.

**Comment by YvonneArnoldus** [comment]
Hi @Mumrau,

I've updated to kubenetes 1.10.5 on Azure and stable/nginx-ingress 0.23.0 and installed it with helm install stable/nginx-ingress --namespace kube-system --set controller.service.externalTrafficPolicy=Local

And now it works fine. So it seems it is solved in either 1.10.5 kubernetes on Azure or stable/nginx-ingress 0.23.0

**Comment by Mumrau** [comment]
Oh all good then.
May I suggest closing the issue?

**Comment by arthuersundar** [comment]
> I'm using AKS w/nginx-ingress configured with a static IP bound to the AKS load balancer (installed nginx-ingress chart with `controller.service.loadBalancerIP=<the IP>`, after having received this IP address as per [this guide](https://docs.microsoft.com/en-us/azure/aks/static-ip)).
> 
> I initially tried to assign `nginx.ingress.kubernetes.io/whitelist-source-range` in one of my ingress resources but saw 403 when accessing from the whitelisted range. Checking the nginx ingress logs (`kubectl logs -f -n kube-system deploy/nginx-ingress-controller`) proved that the client source IP was not being preserved (it is logged at the beginning).
> 
> Reinstalling nginx-ingress with `--set controller.service.externalTrafficPolicy=Local` (which is `Cluster` by default) as per @joakimhellum-in's comment did the trick. From the [Kubernetes docs](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/) on the subject:
> 
> ```
> There are two available options: “Cluster” (default) and “Local”. “Cluster” obscures the client source IP and may cause a second hop to another node, but should have good overall load-spreading. “Local” preserves the client source IP and avoids a second hop for LoadBalancer and NodePort type services, but risks potentially imbalanced traffic spreading.
> ```

Hi pavius, i'm currently facing similar problem with one of my ingress controller. I have reinstalled nginx with --set controller.service.externalTrafficPolicy=Local`,  Still getting 403.any help is appreciated
