### ISSUE TITLE
Unable to delete failed clusters

### ISSUE THREAD

**Issue by devonbarrett** [Azure/AKS#51]
After attempting to create a new cluster in westeurope, I encountered this:

>Operation failed with status: 'Conflict'. Details: Public preview limit of 5 for managed cluster(AKS) has been reached for subscription 97574325-redacted in location westeurope. Please try deleting one or more managed cluster resources in this location before trying to create a new cluster or try a different Azure location.

Which was odd, since I deleted the resource groups the 5 (failed - yeah, also unable to deploy anything to westeurope - east us works fine) previous clusters belonged to.

However, when looking at the output of `az aks list` I still see them in their failed state. The resource groups were deleted >12 hours ago now.

```
[
  ...,
  {
    "id": "/subscriptions/97574325-redacted/resourcegroups/prod/providers/Microsoft.ContainerService/managedClusters/k8s",
    "location": "westeurope",
    "name": "k8s",
    "properties": {
      "accessProfiles": null,
      "agentPoolProfiles": [
        {
          "count": 3,
          "name": "nodepool1",
          "osType": "Linux",
          "storageProfile": "ManagedDisks",
          "vmSize": "Standard_DS2_v2"
        }
      ],
      "dnsPrefix": "k8s-prod-975743",
      "fqdn": null,
      "kubernetesVersion": "1.8.1",
      "linuxProfile": {
        "adminUsername": "azureuser",
        "ssh": {
          "publicKeys": [
            {
              "keyData": "redacted"
            }
          ]
        }
      },
      "provisioningState": "Failed",
      "servicePrincipalProfile": {
        "clientId": "838f6034-redacted"
      }
    },
    "resourceGroup": "prod",
    "type": "Microsoft.ContainerService/ManagedClusters"
  }
]

**Comment by LiliC** [comment]
I am having the same problem. After trying to create a cluster, I received the following error:
`Timeout while polling for control plane provisioning status.`
And the state is :` "provisioningState": "Failed"` 

Tried deleting it from CLI and that failed and cannot delete it manually via the interface either.

**Comment by devonbarrett** [comment]
Yeah that was the same error message I was getting while trying to create them in westeurope.

**Comment by dhirenrouterabbit** [comment]
Same issue ... Even getting the same message on deletion. 

Deployment failed. Correlation ID: cc9fbea9-a524-4231-b539-b95ebafd649b. Timeout while polling for control plane provisioning status

Hope this issue will not add to my bill.

**Comment by azzlack** [comment]
@dhirenrouterabbit We have the same issue, deleting the Resource Group seems to work. (deleting the aks in the process)

**Comment by dhirenrouterabbit** [comment]
Tried today again, seems like deletion is working properly. But creation is still stuck with the same error. Change the region to east US too from europe too. 

Deployment failed. Correlation ID: 77e264d1-f064-44ee-8eb1-7c3b4797c4f0. Operation failed with status: 200. Details: Resource state Failed

I will test by removing some parameters in the operation again.

**Comment by devonbarrett** [comment]
The resource group is no longer there, but I can still see the clusters in the output of `az aks list`. Trying to delete them directly results in:

```
az aks delete -n k8s -g prod
Are you sure you want to perform this operation? (y/n): y
Resource group 'prod' could not be found.
```

But the cluster is definitely still there as it is preventing creating new ones due to the 5 cluster limit still.

**Comment by dhirenrouterabbit** [comment]
I delete it with this command and works properly.

`az aks delete --name name-of-container-service --resource-group "rgTemp"`

**Comment by devonbarrett** [comment]
The failed clusters are still dangling, with no way to delete :(
```
-> az aks list
```
```json
  {
    "id": "/subscriptions/97574325-redacted/resourcegroups/prod/providers/Microsoft.ContainerService/managedClusters/k8s",
    "location": "westeurope",
    "name": "k8s",
    "properties": {
      "accessProfiles": null,
      "agentPoolProfiles": [
        {
          "count": 3,
          "name": "nodepool1",
          "osType": "Linux",
          "storageProfile": "ManagedDisks",
          "vmSize": "Standard_DS2_v2"
        }
      ],
      "dnsPrefix": "k8s-prod-975743",
      "fqdn": null,
      "kubernetesVersion": "1.8.1",
      "linuxProfile": {
        "adminUsername": "azureuser",
        "ssh": {
          "publicKeys": [
            {
              "keyData": "redacted"
            }
          ]
        }
      },
      "provisioningState": "Failed",
      "servicePrincipalProfile": {
        "clientId": "838f6034-redacted"
      }
    },
    "resourceGroup": "prod",
    "type": "Microsoft.ContainerService/ManagedClusters"
  }
```
```
-> az aks delete -n k8s -g prod 
Are you sure you want to perform this operation? (y/n): y                                                                                                                                                                                                                       
Resource group 'prod' could not be found
```

**Comment by hairmare** [comment]
I can reproduce this as well. Additionally if I recreate a Resource Group with the same name the AKS clusters will show back up in the group as if they where never deleted. This does look awfully similar to #33. I was told to re-test this after #53 was fixed in westeurope and will probably open an issue in the portal if it isn't fixed soonish.

**Comment by amanohar** [comment]
@hairmare can you provide more details on?

>  Additionally if I recreate a Resource Group with the same name the AKS clusters will show back up in the group as if they where never deleted.

Also, can you share the resource group and resource name and I will look up the logs.

**Comment by hairmare** [comment]
@amanohar The Resource Group is called "LucasbAKS" and the AKS Cluster ist named "LucasbAKSCluster2".

I initially created the rg on the cli using `az group create` and then deployed a cluster to it using `az aks create`. After the deploy failed (due to #53) I tried deleting the cluster with `az aks delete`. This returned with an exit code of 0 but the cluster is still there when I run `az aks list` again.

```
Name               Location    ResourceGroup    KubernetesVersion    ProvisioningState    Fqdn
-----------------  ----------  ---------------  -------------------  -------------------  --------------------------------------------------------------
LucasbAKSCluster2  westeurope  LucasbAKS        1.8.1                Failed
```

If I delete the RG using `az group delete` the RG gets removed but the cluster still shows up in `az aks list`. If I try to remove it at that stage `az aks delete` errors because the RG does not exist. If I recreate the RG using `az group create` the cluster shows up in the RG as if it was never deleted (in the portal and the cli). Running `az aks delete` makes it disappear from the portal but it still shows up on the `az aks list` cli.

**Comment by amanohar** [comment]
@hairmare thanks for the detailed information. I am investigating the `az group delete` behavior.

From our logs I see that you tried create and delete operation on 11/21 betwee ~ 00:56-08:06 PST. 

While I investigate the delete RG behavior can you try `az aks delete` again as AKS experienced some operation failures during that time frame but the issue is resolved now?

**Comment by hairmare** [comment]
@amanohar I just tried deleting the cluster again and it didn't work:

```console
$ az aks list
Name               Location    ResourceGroup    KubernetesVersion    ProvisioningState    Fqdn
-----------------  ----------  ---------------  -------------------  -------------------  --------------------------------------------------------------
LucasbAKSCluster2  westeurope  LucasbAKS        1.8.1                Failed
$ az aks delete -n LucasbAKSCluster2 -g LucasbAKS
Are you sure you want to perform this operation? (y/n): y
$ echo $?
0
$ az aks list
Name               Location    ResourceGroup    KubernetesVersion    ProvisioningState    Fqdn
-----------------  ----------  ---------------  -------------------  -------------------  --------------------------------------------------------------
LucasbAKSCluster2  westeurope  LucasbAKS        1.8.1                Failed
```

**Comment by amanohar** [comment]
@hairmare thanks for your patience and trying again. I am following up with partners teams on this and will get back to you. 

Can you also confirm if agent VMs and the resource group (that contains agent VMs) `MC_LucasbAKS_LucasbAKSCluster2_westeurope` has been deleted? (logs does indicate that agents have been deleted).

**Comment by amanohar** [comment]
@hairmare we have reconciled the cache on our side. Can you try deleting again?

**Comment by devonbarrett** [comment]
Exact same experience as @hairmare.

Still seeing the clusters in the output of `az aks list`

**Comment by LiliC** [comment]
Mine is still there as well, just checked. But I am pretty sure I deleted it last week, I double checked as it did not work straight away.

**Comment by hairmare** [comment]
@amanohar I just retried deleting the cluser agin using `az aks delete` and it worked! It looks like reconciling the cache worked.

**Comment by amanohar** [comment]
@hairmare thanks for reporting back and confirming.

**Comment by amanohar** [comment]
@LiliC and @devonbarrett I recommend opening separate issues and providing details like resource group name, resource name, when you tried the operation, region etc. as this expedites investigation.

**Comment by devonbarrett** [comment]
The resource groups reappeared in the portal, and deleting them again resulted in the failed clusters no longer appearing in the output of `az aks list`.

Closing - thanks!
