### ISSUE TITLE
Azure Bastion Integration with AKS - Az AKS CLI integration

### ISSUE THREAD

**Issue by mayasingh17** [Azure/AKS#5269]
Azure Bastion Integration with AKS enables customers to access private clusters using Az AKS Bastion via a Bastion Tunnel. AKS customers who deploy private clusters or public clusters with API server authorized IP ranges often have a need to access their cluster API server from outside the usual scope – whether this is developers who are working from home, a private cluster deployed in an island virtual network. Traditional solutions like VPN servers and jump boxes can be cumbersome and costly to set up and maintain. With Azure Bastion support for AKS, Azure Bastion can now be used to provide a secure tunnel from the local machine to the AKS API server, allowing users to utilize their regular Kubernetes tooling seamlessly. This integration simplifies access, reduces setup time, and enhances security by eliminating the need for exposing public endpoints

**Comment by mayasingh17** [comment]
https://learn.microsoft.com/en-us/azure/bastion/bastion-connect-to-aks-private-cluster, we are working to enable clusters with public FQDN disabled

**Comment by mayasingh17** [comment]
We are eager to hear your feedback on this feature - please let us know how this is working for you in the comments of this issue.

**Comment by audunsolemdal** [comment]
> We are eager to hear your feedback on this feature - please let us know how this is working for you in the comments of this issue.

The feature seems very promising apart from a few things:

1. support clusters with public FQDN disabled, which you are working on (great!)
2. Would also like [this bug to be fixed](https://github.com/Azure/azure-cli-extensions/issues/9060), else I will still prefer using a cheap jumpbox VM where my shell has aliases set up.
3. The azure cli commands to run when the bastion host and the AKS cluster are in two different subscriptions, I was able to get this to work, but it was quite unintuitive.

**Comment by stevekuznetsov** [comment]
@mayasingh17  small feedback - the learn.microsoft.com docs should be updated with _how_ to set up the bastion host for AKS, not just assuming everyone has done it - most of the previous azure bastion examples also use a VM jumpbox which is obviously not necessary now, so a clear .bicep/Infrastructure-as-Code example would be great. I implemented such in [this PR](https://msazure.visualstudio.com/AzureRedHatOpenShift/_git/sdp-pipelines/pullrequest/13976902) in case you want some example. It would also be super useful if we could specify the exact Azure RBAC permissions required to use this feature - the user needs to have AKS permissions to get credentials, and some others to establish the bastion, but it is not clear to me which.

**Comment by mbifeld** [comment]
Thanks for the feedback @stevekuznetsov. Will work on updating the docs with your suggestions. Also, the [PowerShell bug](https://github.com/Azure/azure-cli-extensions/issues/9060) is fixed, and Bastion now works with clusters with public FQDN disabled.

**Comment by audunsolemdal** [comment]
>  and Bastion now works with clusters with public FQDN disabled.

Are there any caveats to get this working? I've upgraded my azure CLI + extensions to the latest versions.

Bastion towards my private cluster **with** public FQDN enabled, my setup works without issues. For my private cluster **without** public FQDN enabled I end up with this:

```
k get pods
E1211 07:58:03.488365   35064 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://localhost:52560/api?timeout=32s\": net/http: TLS handshake timeout"
```

**Comment by mbifeld** [comment]
Hi @audunsolemdal, the only requirement is having your Bastion be up to date, which is done automatically by Microsoft.

If you're comfortable, can you please send your AKS cluster and Bastion resource IDs to me at mbifeld@microsoft.com so we can investigate?

**Comment by audunsolemdal** [comment]
>
> If you're comfortable, can you please send your AKS cluster and Bastion resource IDs to me at [mbifeld@microsoft.com](mailto:mbifeld@microsoft.com) so we can investigate?

For the public - the error was cryptic, but the reasoning was that Bastion in my network setup didn't resolve the private DNS.
Creating a direct vnet link between the bastion VNET and the privatelink.<clusterregion>.azmk8s.io seems to do the trick.

The issue was more clear in the Azure Portal via the Bastion --> Connection troubleshoot view, where connecting via the private IP works, but connecting via the private FQDN fails to resolve.

**Comment by audunsolemdal** [comment]
By the way, I would also request that it should be possible for the az aks bastion command to use a pre-existing kubeconfig file. Would that be possible? The current experience which generates a new kubeconfig in APPDATA and sets it via env vars works fine in that shell, but when integrating with external applications, e.g. Headlamp it causes an unfortunate UX.

I posted a more specific issue in the AKS Desktop repo https://github.com/Azure/aks-desktop/issues/92

**Comment by mbifeld** [comment]
@audunsolemdal Glad we got the error resolved. We're working on more descriptive error outputs. For using a pre-existing kubeconfig file, that's a good idea. I will check on the feasibility of implementing this and report back.

**Comment by mbifeld** [comment]
@audunsolemdal Being able pass in an existing kubeconfig is being added in https://github.com/Azure/azure-cli-extensions/pull/9509#pullrequestreview-3667935972.

**Comment by audunsolemdal** [comment]
Question regarding this.

I have a PIM group membership which I can activate when i need administrative permissions for my clusters.
Usually after activating this I run `kubelogin remove-tokens` to re-authenticate with a fresh token. I can't get this to work when using the `az aks bastion` command. Is there another way to reset the token in order to force a fresh authentication?


My kubeconfig user auth looks like this:
```
- name: clusterUser_xxx_yyy
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --login
      - azurecli
      - --server-id
      - 6dae42f8-4368-4678-94ff-3960e28e3630
      command: kubelogin
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```
