### ISSUE TITLE
Tunnel dies quickly after issuing az aks browse

### ISSUE THREAD

**Issue by MXClyde** [Azure/AKS#68]
When using "az aks browse" to access the Kubernetes Dashboard, the tunnel stops working after a few minutes (of inactivity). Can this behaviour be modified so that the tunnel keeps working longer?

**Comment by khenidak** [comment]
Is it the tunne itself dies or your socket dies (as in if you re do aks browse.. you will connect normally)

**Comment by MXClyde** [comment]
Issuing aks browse will re-establish the possibility to open the dashboard. Need to do this in another Bash for Windows Shell because something about aks browse makes it impossible to type a subsequent command in the same shell. (will try it again and write a more detailed explanation, if necessary)

**Comment by khenidak** [comment]
Please do.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MXClyde** [comment]
Allright video: https://youtu.be/NOIhpp2C-LI
This is all on Windows 10.

**Comment by khenidak** [comment]
@MXClyde Thanks, truly appreciated 

Re - **not able to execute any commands after browse**. The reason behind that is the CLI runs kubectl proxy, this process does not return (exit) and is used to forward the traffic from localhost:port->to api-server->Dashboard-Svc. If you want to be able to execute commands you run ```kubectl proxy &``` (or just start another shell). 

As for tunnel dying, The tunnel itself does not die, the *inactive* socket is quickly killed. This helps in best utilize network resources, I will however look into increasing the timeout. Please note i will consider this a bit of a low pri for the time being. 

Again thank you for detailed reporting.

**Comment by MXClyde** [comment]
Thanks for the explanation, when using "kubectl proxy" on ACS-Kubernetes the timeout seems to be longer  already (never experienced this, at least).

**Comment by wilsondy** [comment]
+1  Dashboard dies every few minutes.

**Comment by kareem-workfit** [comment]
+1 Also experiencing this.

**Comment by mavencode01** [comment]
@khalidawwad can we bump this priority up, it becomes increasingly frustrating and kills my demo every time.

**Comment by novaterata** [comment]
I have to constantly kill the tunnel and re-run `az aks browse` or else the dashboard won't reload pages. Is this the same problem?

**Comment by Zimmergren** [comment]
I know this is not a solution, and I too would love to see this as a configurable param when opening the dashboard connection; However here's my current workaround for keeping the connection alive (tldr: auto-update logs and keep that open in a tab...)

https://github.com/Azure/AKS/issues/285#issuecomment-378888912

Not a pretty solution down the road..

**Comment by derekperkins** [comment]
I don't understand the purpose of the command. Just using `kubectl proxy` works great.

**Comment by thebitguru** [comment]
@derekperkins I thought `proxy` had the same issue.  Does your connection stay active if you don't do anything for a few minutes?

**Comment by derekperkins** [comment]
I've encountered the same issues listed here with `az aks browse`, so I know what the issue is. `kubectl proxy` however does not timeout on me, and even does a pretty good job at recovering connections if my computer goes to sleep or if I change my network (VPN, switching wifi, etc).

**Comment by thebitguru** [comment]
Interesting.  I will have to try that again because I thought it was also timing out after a little bit.

How about `kubectl port-forward` to a pod?  Does that keep the connection open as well?

**Comment by derekperkins** [comment]
@thebitguru I rarely use it, so I don't know how well it works. As a sidenote, if you use the 1.10 kubectl binary, you can port forward to a service without having to pick a pod.

**Comment by rfum** [comment]
kubectl proxy also works fine for me.

**Comment by derekperkins** [comment]
Yes, AKS. `kubectl proxy` has worked great for me on 4-5 clusters spanning the listed versions over the past 6 months - it has never not worked well for me.
Server: 1.8.7, 1.9.2, 1.9.6
Client: 1.9.x, 1.10.1, 1.10.2

**Comment by thebitguru** [comment]
I can confirm that I am using AKS.  Here are versions:
Server: 1.9.6
Client: 1.10.0

**Comment by subesokun** [comment]
I was trying now `kubectl proxy` but still having the same issue. After a couple of minutes the proxy is dying with following message:
```
I0528 08:49:51.941173    1275 logs.go:49] http: proxy error: context canceled
I0528 08:49:58.976043    1275 logs.go:49] http: proxy error: unexpected EOF
I0528 08:49:58.976088    1275 logs.go:49] http: proxy error: unexpected EOF
```
The only trick that did work for me to keep the proxy alive was to enable auto-refresh on any log in the Kubernetes dashboard.

**Comment by mwelch-ptc** [comment]
I have this same issue with `az aks browse`, `kubectl proxy`, and `kubectl port-forward`. All of these have very short idle timeouts that give no clue that it has actually timed out except that things stop working. I too use the "log auto-refresh" workaround for the dashboard but this doesn't help for things like `kubectl port-forward`.

**Comment by patrickmslatteryvt** [comment]
I opened a case with MS and provided copious logs for them to dig through. They refused to acknowledge that there is a problem with `az aks browse` and blamed this issue in Kubernetes instead:
https://github.com/kubernetes/kubernetes/issues/63727
However I cannot replicate this issue on any Kubernetes cluster bar those on AKS...

**Comment by novaterata** [comment]
Yeah I don't have an issue with kubectl proxy, only az aks browse

**Comment by cgroves** [comment]
Our experience is the same, this doesn't occur in on-prem Kubernetes. Only when using az aks browse.

**Comment by wouterhund** [comment]
@khenidak This is a big problem for `kubectl port-forward`. Gaining access to in-cluster resources becomes really difficult if the TCP sockets get killed every minute or two. This problem does not exist for any other kubernetes deployments I've used.

**Comment by khenidak** [comment]
This has been fixed few weeks back and we are rolling out steadily since. @ritetonikhil can add more details

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by wouterhund** [comment]
@khenidak Glad to hear! Looking forward to seeing this fixed in the westeurope region. By the way, that `@mention` seems to have failed.

**Comment by rite2nikhil** [comment]
We are in process of rolling out a fix for this. Thanks all for your patience

**Comment by seanknox** [comment]
Believe this fix is now rolled out globally. Please re-open if you're still having issues.

**Comment by patrickmslatteryvt** [comment]
@seanknox 
So how exactly is the fix rolled out?
Is this purely a server side fix? Or do we need to have a specific version of the `az` client?

I'm using `azure-cli (2.0.43)` and connecting to AKS clusters running Kubernetes v1.11.1 and I'm still having frequent timeouts from Win10, macOS and Fedora clients using the latest Chrome.
It seems to work a lot better if I use the Edge browser but that's not an option on my primary OS (Fedora) so I have to resort to having a second Chrome tab that refreshes every 30 seconds to keep the connection alive.

**Comment by hafizramly** [comment]
Still seeing this issue happening with azure-cli (2.0.44). This also seems related to #313 

My AKS cluster are running on 1.11.3

**Comment by subesokun** [comment]
So far the connection to the Kube Dashboard has been stable (didn't timeout) when opening it via the VSCode Kuberentes extensions. Unfortunately, since a couple of days I'm facing now also there these timouts :(

**Comment by WebstudioThomHubers** [comment]
Please reopen since issue is still present.

**Comment by kanadaj** [comment]
@rite2nikhil any updates on this?

**Comment by EvgenyKhaliper** [comment]
Is the fix on it's way ?

**Comment by thomhubers** [comment]
It seems a bit better after I did a kubernetes update to 1.10.

**Comment by JonasDeGendt** [comment]
Still experiencing this as well, turning on auto-refresh of logs on a pod as a workaround still works though.

**Comment by SJrX** [comment]
I'm also still experiencing this :(

**Comment by GuyPaddock** [comment]
I, too, have this issue. The workaround right now is a loop that just restarts `az aks browse` if it dies, after a 2 second sleep (to ensure the tunnel can be stopped with CTRL+C).

https://github.com/GuyPaddock/inveniem-nextcloud-azure/blob/master/nextcloud-aks/launch_aks_dashboard.sh

**Comment by jitcoder** [comment]
happening here as well
azure-cli                         2.0.60

**Comment by prune998** [comment]
Issue still there.
Had the `same` issue with all my Ingress... It can be tweaked by increasing the Load-Balancer Idle timeout... how do we change this parameter for the Cluster API ? 

`azure-cli (2.0.55)`
cluster is 1.11.5

issue exist with : 
- kubectl proxy
- az aks browse
- kubectl port-forward
- kubectl exec

Had zero issue for years using AWS(Kops), AWS EKS or GKE... 

@seanknox we need help on that ! Please don't let us down like Microsoft is known to

**Comment by jnoller** [comment]
AKS Creates an Azure Load Balance in front of the api server ingress. Per the link here: https://stackoverflow.com/questions/50706483/what-azure-kubernetes-aks-time-out-happens-to-disconnect-connections-in-out 

Basic Azure LBs have 4 min timeouts while standard ones have a 30 min timeout. Currently, we are working on support for Standard LBs to remove the dependency on Basic LBs. We've seen this issue in support tickets and it's directly tied to the Basic LB behavior and timeouts.

I will file a repair item to see if we can expose the timeout setting for that LB without introducing significant complexity to the API / CLI and underlying management system.

**Comment by jnoller** [comment]
Reopened, marked known-issue.

**Comment by prune998** [comment]
thanks @jnoller 
Can you confirm that this `Azure Load Balance in front of the api server` can't be seen in the Azure Portal ? 
So, in fact, we don't have any way to configure it ? 
Let me know if I'm wrong here :)

Regards.

**Comment by jnoller** [comment]
@prune998 The LB is in the MC_* resource group which is read-only, no write.

**Comment by prune998** [comment]
Well, I don't see it in my list. What kind of IAM role should I get to see it ? 
Thanks

**Comment by jnoller** [comment]
@prune998 You would need subscription administrator access, and also, you can not change the value. As I said, it's read-only, and the timeout is the default 4 minutes.

**Comment by prune998** [comment]
Thanks @jnoller, understood.
So this 2 years old issue was closed knowing the solution was not implemented ? :)

**Comment by kpapadatos** [comment]
My workaround:
```cmd
# Have concurrently installed
npm i -g concurrently

# Put this command in a file and use it instead
concurrently "az aks browse --resource-group <RG_NAME> --name <AKS_CLUSTER>" "node -e ""setInterval(() => { require(`http`).get('http://127.0.0.1:8001') }, 5e3)"""
```

**Comment by prune998** [comment]
@kpapadatos while I like workaround, I'd rather have the problem (which is unique to AKS) solved !
My personal workaround would be to switch back to GKE... :)

**Comment by djj0809** [comment]
This is really an annoying issue, and not a complicated one, you guys should put more efforts on this:)

**Comment by AlexcGray** [comment]
I'm also still experiencing this issue with both aks browse & kubectl proxy. Running Kube v1.12.6 and Azure-CLI v2.0.32

**Comment by jnoller** [comment]
@AlexcGray This is a known issues which is not fixed. This issue will be closed when AKS supports the Standard Load Balancer on azure and moves away from the basic load balancer in front of the API server. The Basic LB has a default timeout of 4 minutes, and a max of 30 minutes (hard cap)

**Comment by javafrog** [comment]
I'm having the same issue.

**Comment by cpunella** [comment]
Hi, any timeline for the fix? if you need to work all day with AKS it's frustrating...

**Comment by prune998** [comment]
@cpunella prepare to be frustrated :)
At least you could go to your Load-Balancing resources and increase the timeout to 30 mins (i'm even not sure this specific issues comes from this LB's timeout or another internal you can't change)

**Comment by jnoller** [comment]
SLB support is coming shortly, it’s in active development https://github.com/Azure/AKS/projects/1

**Comment by fvztdk** [comment]
If you have 2FA enabled this should give you plenty of time to input it. The type of jerry rig that you need to come to make something working on Azure impress me everyday
```
concurrently "az aks browse --resource-group <RG_NAME> --name <AKS_CLUSTER>" "node -e ""setInterval(() => { require(`http`).get('http://127.0.0.1:8001') }, 5e3)""" --restart-tries 10 --restart-after 10000
```

**Comment by xavierrh** [comment]
Hi,
Same issue on our side. As a workaround, we launch the following command in another PowerShell prompt to keep the tunnel alive:
`while(1) { Invoke-RestMethod -Uri 127.0.0.1:8001 ; start-sleep -seconds 1 }`

Hope it helps in the meanwhile.

**Comment by cursorme** [comment]
Same issue here after deploying a postgresql helm chart:

kubectl port-forward --namespace default svc/xxxxxxx-postgresql 5432:5432
Forwarding from 127.0.0.1:5432 -> 5432
Forwarding from [::1]:5432 -> 5432
Handling connection for 5432
Handling connection for 5432
Handling connection for 5432
E0930 09:58:51.840461   22293 portforward.go:233] lost connection to pod

The kubelet has 4h timeout that seems that are not beign honored !

**Comment by palma21** [comment]
Closing stale issue after 30d inactivity
