### ISSUE TITLE
Namespaces stuck in Terminating state

### ISSUE THREAD

**Issue by tehKapa** [Azure/AKS#733]
I tried to delete two namespaces from my AKS development cluster, but they've been stuck in _Terminating_ state for over two days.

**Environment**:
- Kubernetes version: v1.11.4
- Size of cluster: 1

```
kubectl get ns
NAME                  STATUS        AGE
default               Active        108d
gitlab-build          Active        41d
gitlab-managed-apps   Active        41d
istio-system          Terminating   57d
kube-public           Active        108d
kube-system           Active        108d
kubernator            Active        83d
logging               Terminating   34d
```

**Comment by tehKapa** [comment]
Yes, I checked with `kubectl --namespace=logging get all` and there are no pending resources. I've also eliminated PVC and Secrets.

```
kubectl describe namespace logging
Name:         logging
Labels:       name=logging
Annotations:  <none>
Status:       Terminating

No resource quota.

No resource limits.
```

**Comment by deepforu47** [comment]
Having the same issue with the same setup -

Environment:

Kubernetes version: v1.11.4
Size of cluster: 1

**Comment by tomasr** [comment]
I've had this happen in the past. Couldn't figure out what causes it, but they eventually clear out after a few days (I suspect this has to do with reboots or restarts going on the master side, rather than anything on the worker node side of things).

**Comment by kajanth** [comment]
I have seen the issue in our cluster's as well on AKS 1.11.4. Caused by `spec:
    finalizers:
    - kubernetes` in the namespace manifest.

There is a work around for this 
1) `kubectl get ns <namespace> -o json > namespace.json`
2) remove the `- kubernetes` in the temp.json
3) `kubectl proxy`
4) http://127.0.0.1:8001/api/v1/namespaces/<namespace>/finalize

then delete the namespace this has shown to be working for us.

**Comment by deepforu47** [comment]
@kajanth - Yes, workaround is available and its working. But need to be fixed.

**Comment by jnoller** [comment]
This is a upstream Kubernetes (not AKS) issue. We can confirm this impacts 1.11.x - I believe this is the main upstream bug tracking this https://github.com/kubernetes/kubernetes/issues/60807 however there are many bugs filed tracking this same behavior with the finalizers.

We will be unable to resolve this until a new upstream release which addresses this issue is released by the Kubernetes team. Marking as a known issue.

**Comment by pkrishnath** [comment]
+1

**Comment by kmoussa** [comment]
Any updates on this issue? it's still persists - AKS Cluster 1.14.6 and 1.14.7 ??!

**Comment by marcoboffi** [comment]
+1 with AKS Cluster 1.14.8

**Comment by andyzhangx** [comment]
I found my namespace is in also in terminating state for a long time, and by using `k get ns name -o yaml`, could get some useful info, it's usually caused by finalizer, below is an example:

```
# k get ns azuredisk-3226 -o yaml
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2020-02-07T08:31:35Z"
  deletionTimestamp: "2020-02-07T08:34:30Z"
  labels:
    e2e-framework: azuredisk
    e2e-run: 825b0e06-b609-4a1f-90ec-7e5a03d004be
  name: azuredisk-3226
  resourceVersion: "820013"
  selfLink: /api/v1/namespaces/azuredisk-3226
  uid: 81eb6e5d-cfdd-4fb3-bea5-7bdf25244af4
spec:
  finalizers:
  - kubernetes
status:
  conditions:
  - lastTransitionTime: "2020-02-07T08:34:35Z"
    message: All resources successfully discovered
    reason: ResourcesDiscovered
    status: "False"
    type: NamespaceDeletionDiscoveryFailure
  - lastTransitionTime: "2020-02-07T08:34:35Z"
    message: All legacy kube types successfully parsed
    reason: ParsedGroupVersions
    status: "False"
    type: NamespaceDeletionGroupVersionParsingFailure
  - lastTransitionTime: "2020-02-07T08:34:35Z"
    message: All content successfully deleted, may be waiting on finalization
    reason: ContentDeleted
    status: "False"
    type: NamespaceDeletionContentFailure
  - lastTransitionTime: "2020-02-07T08:34:35Z"
    message: 'Some resources are remaining: volumesnapshots.snapshot.storage.k8s.io
      has 1 resource instances'
    reason: SomeResourcesRemain
    status: "True"
    type: NamespaceContentRemaining
  - lastTransitionTime: "2020-02-07T08:34:35Z"
    message: 'Some content in the namespace has finalizers remaining: snapshot.storage.kubernetes.io/volumesnapshot-bound-protection
      in 1 resource instances'
    reason: SomeFinalizersRemain
    status: "True"
    type: NamespaceFinalizersRemaining
  phase: Terminating
```

**Comment by noamichael** [comment]
@andyzhangx Is your solution to remove the finalizer? There is usually some reason the finalizer gets stuck and I don't think this issue is resolved.

**Comment by andyzhangx** [comment]
> @andyzhangx Is your solution to remove the finalizer? There is usually some reason the finalizer gets stuck and I don't think this issue is resolved.

@noamichael 
try following steps to remove finalizers, need to mention this issue is not AKS specific, mainly it's due to wrong delete operations on objects, finalizers, etc.
  - Get all the resources in the namespace and delete if they’re some resources:
```
kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get --show-kind --ignore-not-found -n $NAMESPACE
```
  - Delete finalizers:
```
kubectl get namespaces $NAMESPACE -o json | jq '.spec.finalizers=[]' > /tmp/ns.json
kubectl proxy &
curl -k -H "Content-Type: application/json" -X PUT --data-binary @/tmp/ns.json http://127.0.0.1:8001/api/v1/namespaces/$NAMESPACE/finalize
```

**Comment by lgmorand** [comment]
I've the same issue on my cluster (1.16.7). Workaround given by Andy works, but was I don't understand is that if I delete my cluster and recreate it, the bug comes backs for every namespace. It's a scripted cluster but I didn't find yet, what's causing the issue

**Comment by AnishJS** [comment]
Any update on this? It's a very persistent issue.

**Comment by caruccio** [comment]
Simply removing the finalizers is not the way to go, since something may got stuck into the namespace.

Following this tip from https://github.com/kubernetes/kubectl/issues/151#issuecomment-402003022 I could identify an object still exists:

```
$ kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get --show-kind --ignore-not-found  -n istio-system
NAME                                             REVISION   AGE
istiooperator.install.istio.io/installed-state              2d9h
```

Inspecting the object I've found it alse has a finalizer: 

```
$ kgn istio-system istiooperator.install.istio.io -o yaml | grep -A 2 finalizers
    finalizers:
    - istio-finalizer.install.istio.io
    generation: 3
```

Which makes sense since I just `kubectl delete ns/istio-system $(kubectl crd -o name | grep istio)` expecting everything to simply work. Turns out istio operator was removed before the istiooperator.install.istio.io object, leaving the finalizer behind. That kept the namespace non-empty, preventing it to be removed from kubernetes.
Removing the finalizer by hand did remove the object and then the namespace.
